### ISSUE TITLE
Handle panics during checking

### ISSUE THREAD

**Issue by jeffa5** [stateright/stateright#29]
Would it be possible to catch panics during checking and cleanly terminate the process, maybe with a typical report?

**Comment by jonnadal** [comment]
Absolutely. This is something that has bothered me as well, and I would love to surface these in the Explorer UI. Recording all panics seems like a nonstarter, so one option is to simply surface one panic (or up to one per thread, but even that seems more than necessary). Off the top of my head I imagine it would involve:

1. Add the needed "panic" field to each checker (e.g. `DfsChecker`).
2. Update the `Checker::join` implementations accordingly.
3. Introduce a `Checker::panic` accessor.
4. Revise the `Reporter` implementation(s) and the Explorer UI.
5. Make changes so that panics aren't missed when asserting properties (`Checker::assert_properties` should probably propagate the panic). That could possibly be done at a lower level like `Checker::assert_no_discovery`.
